from setuptools import setup

setup(
    name='phylofisher',
    version='0.1',
    packages=['phylofisher'],
    scripts=['phylofisher/fisher.py',
             'phylofisher/config.py',
             'phylofisher/fishing_net.py',
             'phylofisher/forest.py',
             'phylofisher/forge.py',
             'phylofisher/informant.py',
             'phylofisher/lumberjack.py',
             'phylofisher/purge.py',
             'phylofisher/build_dataset.py',
             # 'phylofisher/missing_data.py',
             'phylofisher/trimming.py',
             'phylofisher/utilities/missing_data2.py',
             'phylofisher/utilities/AgentEllie.py',
             'phylofisher/utilities/AgentEllie2.py',
             'phylofisher/utilities/len_filter.py',
             'phylofisher/utilities/len_filter2.py',
             'phylofisher/utilities/fast_tax_removal.py',
             'phylofisher/utilities/heteroevolving_sites.py',
             'phylofisher/utilities/no_gap_stops.py',
             'phylofisher/utilities/add_aln_length.py',
             'phylofisher/utilities/sub.py',
             'phylofisher/utilities/pre_trimal.py'],
    url='',
    license='MIT',
    author='david',
    author_email='zihaladavid@gmail.com',
    description=''
    )