version: 2.1

jobs:
  # Run linting
  lint:
    docker:
      - image: mambaorg/micromamba
    steps:
      - checkout
      - run: "micromamba install pylint"
      - run: "pylint phylofisher --exit-zero"
  # Run tests
  test:
    docker:
      - image: mambaorg/micromamba
    steps:
      - checkout
      - run: "micromamba install -y -c conda-forge -c bioconda phylofisher pytest python=3.7.10"
      - run: "conda remove -y --force phylofisher"
      - run: "pip install --no-deps ."
      - run: "pytest"

# Workflows
workflows:
  commit-status:
    jobs:
      - lint
      - test
