version: 2.1

jobs:
  # Run linting
  lint:
    docker:
      - image: continuumio/anaconda3
    steps:
      - checkout
      - run: "conda install pylint"
      - run: "pylint phylofisher --exit-zero"
  # Run tests
  test:
    docker:
      - image: continuumio/anaconda3
    steps:
      - checkout
      - run: "conda install -y -c conda-forge mamba"
      - run: "mamba create -n fisher -y -c conda-forge -c bioconda phylofisher pytest"
      - run: "conda init bash"
      - run: "echo $SHELL"
      - run: "conda activate fisher"
      - run: "conda remove -y --force phylofisher"
      - run: "pip install --no-deps ."
      - run: "pytest"

# Workflows
workflows:
  commit-status:
    jobs:
      - lint
      - test
