version: 2.1

jobs:
  lint:
    docker:
      - image: continuumio/anaconda3
    steps:
      - checkout
      - run: "conda install pylint"
      - run: "pylint phylofisher --exit-zero"
  
  test:
    docker:
      - image: continuumio/anaconda3
    steps:
      - checkout
      - run: "conda install -y -c conda-forge mamba"
      - run: "mamba install -y -c bioconda phylofisher pytest"
      - run: "conda remove --force -y phylofisher"
      - run: "pip install --no-deps ."
      - run: "pytest"

workflows:
  commit-status:
    jobs:
      - lint
      - test
