version: 2.1

jobs:
  lint:
    docker:
      - image: mambaorg/micromamba
    steps:
      - checkout
      - run: "micromamba install pylint"
      - run: "pylint phylofisher --exit-zero"
  
  test:
    docker:
      - image: mambaorg/micromamba
    steps:
      - checkout
      - run: "micromamba install -y -c bioconda phylofisher pytest pip"
      - run: "micromamba remove --force -y phylofisher"
      - run: "pip install --no-deps ."
      - run: "pytest"

workflows:
  commit-status:
    jobs:
      - lint
      - test
