name: Publish

# Triggers to run on new release
on: [release]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Sets up stuff
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  
  # Publish to PyPi
  publish-to-pypi:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build wheels
        run: echo
      - name: Upload to pypi
        run: twine upload

  # Publish to Anaconda
  publish-to-anaconda:
    needs: publish-to-pypi
    runs-on: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Build package
        run: echo Hello, world!
      - name: Upload to conda
        run: anaconda -t ${{ secrets.ANACONDA_TOKEN }}

